version: "3.1"

volumes:
    db-data:

services:
    mysql:
      image: mysql:5.6
      container_name: ${PROJECT_NAME}-mysql
      working_dir: /application
      volumes:
        - db-data:/application
      environment:
        - MYSQL_ROOT_PASSWORD=vb
        - MYSQL_DATABASE=vb
        - MYSQL_USER=vb
        - MYSQL_PASSWORD=vb
      ports:
        - "3306:3306"

    # webserver:
    #   image: nginx:alpine
    #   container_name: ${PROJECT_NAME}-webserver
    #   working_dir: /application
    #   volumes:
    #     - .:/application
    #     - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    #   ports:
    #     - "80:80"

    # php-fpm:
    #   build: docker/php-fpm
    #   container_name: ${PROJECT_NAME}-php-fpm
    #   working_dir: /application
    #   volumes:
    #     - .:/application
    #     - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
